### ISSUE TITLE
Issues with the pcb files

### ISSUE THREAD

**Issue by Veund** [zephray/NekoCart-GB#5]
I recently started doing surface mount soldering and wanted to give your cart a try as its something id actually use, the issue is that the gerbers aren't available and altium is kind of expensive.

if you upload the files in PCB ASCII Version 5.0 - select to save the current PCB document in PCB ASCII version 5.0 format I could import to EasyEDA and make changes or produce gerbers for upload to something like osh park

regards veund

**Comment by zephray** [comment]
Hi, yeah I know this issue, sorry about that. I have migrated to use KiCAD in all my new projects. But for these kinda done projects, I didn't really invest a lot of time to convert them to KiCAD. Actually, I no longer have access to the Altium Designer, which is also an issue for me... I guess the only thing I can say now is that I am more than happy to take Pull Requests or just adding links to people who redrew the thing in gEDA/ KiCAD/ EasyEDA, but I am probably not gonna do it myself in the near future.

**Comment by Veund** [comment]
Thanks for the response I'll keep trying with my attempt to get them converted

**Comment by Veund** [comment]
managed to convert the pcb files to ascii have submitted a pull request in a zip file
